app/course/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileField, FileRequired

#查询课程表单
class JoinCourseForm(FlaskForm):
    id_or_name = StringField("课程id或课程名", validators=[DataRequired(), Length(1, 12)])
    submit = SubmitField("查询")


#发布公告表单
class AnnouncementForm(FlaskForm):
    title = StringField("标题", validators=[DataRequired(), Length(1, 20)])
    content = TextAreaField("内容", validators=[DataRequired(), Length(1, 300)])
    submit = SubmitField("发布")


#创建课程表单
class CreateCourseForm(FlaskForm):
    name = StringField("课程名", validators=[DataRequired(), Length(1, 20)])
    about_course = TextAreaField("课程介绍", validators=[DataRequired(), Length(1, 300)])
    college = StringField("学院", validators=[DataRequired(), Length(1, 20)])
    submit = SubmitField("创建")


#发布资源表单
class PublishResourceForm(FlaskForm):
    name = StringField('资源名 (不能出现中文)', validators=[DataRequired(), Length(1, 50)])
    file = FileField('资源文件', validators=[FileRequired()])
    submit = SubmitField('上传')

app/course/__init__.py
from flask import Blueprint

course = Blueprint('course', __name__)

from . import views

app/course/views.py
# -*- coding: utf-8 -*-
import json

from flask import url_for, render_template, redirect, request, current_app, session, Response
from .. import db
from app.models import Teacher, User, Course, StudentCourse, Announcement, Test, Answer, CheckTest, Student
from . import course
from flask_login import login_required, current_user
from .forms import *
from config import basedir, resources_base_dir
from ..utils import *
import re
from ..decorators import *

#TODO:显示所有课程，学生显示选课，老师显示开设的课
@course.route('/')
@login_required
def index():
    if current_user.role is not None and current_user.role.name == 'Student':
        page = request.args.get('page', 1, type=int)
        pagination = current_user.student.courses.paginate(
            page, per_page=current_app.config['FLASKY_COURSE_PER_PAGE'],
        error_out=False)
        courses = [item.course for item in pagination.items]
        return render_template('course/index.html', courses=courses, pagination=pagination)
    elif current_user.role.name == 'Teacher':
        page = request.args.get('page', 1, type=int)
        pagination = current_user.teacher.courses.paginate(
            page, per_page=current_app.config['FLASKY_COURSE_PER_PAGE'],
        error_out=False) #老师创建的课程
        courses = [item for item in pagination.items]
        return render_template('course/index.html', courses=courses, pagination=pagination)


#TODO:加入课程
@course.route('/query-course', methods=['GET', 'POST'])
@login_required
def query_course():
    form = JoinCourseForm()
    if form.validate_on_submit():
        session['course_id_or_name'] = form.id_or_name.data #存到session里
        return redirect(url_for('.courses')) #重定向到courses路由，交给courses函数处理
    return render_template('course/query_course.html', form=form)


@course.route('/join-course/<int:course_id>')
@login_required
@permission_required(Permission.JOINCOURSE)
def join_course(course_id):
    record = StudentCourse(
        student_id=current_user.student.student_id,
        course_id=course_id
    )
    db.session.add(record)
    db.session.commit()
    return redirect(url_for('.index'))



#显示查询出的所有课程
@course.route('/courses', methods=['POST', 'GET'])
@login_required
def courses():
    id_or_name = session['course_id_or_name']
    if re.match(r'^[0-9]*$', id_or_name):
        courses = Course.query.filter_by(course_id=id_or_name).all()
    else:
        courses = Course.query.filter_by(name=id_or_name).all()
    return render_template('course/courses.html', courses=courses)


#TODO:删除课程路由，删除完之后重定位到index，相当于刷新了页面
@course.route('/drop-course', methods=['POST', 'GET'])
@login_required
def drop_course():
    if current_user.role.name is not None:
        if current_user.role.name == 'Student': #如果是学生就退出班级，在StudentCourse表中删掉一条记录
            course_id = request.values.get('course_id')
            record = StudentCourse.query.filter_by(course_id=course_id, student_id=current_user.student.student_id).first()
            db.session.delete(record)
            db.session.commit()
        #TODO
        else: #如果是老师或者管理员，就直接解散，删掉Course表中的一条记录
            course_id = request.values.get('course_id')
            record = Course.query.filter_by(course_id=course_id).first()
            db.session.delete(record)
            db.session.commit()
            drop_messsage_table(course_id) #解散的时候要在mysql中删表
        return redirect(url_for('.index'))
    else:
        return render_template('500.html')


#老师创建课程视图
@course.route('/create-course', methods=['GET', 'POST'])
@permission_required(Permission.CREATECOURSE)
def create_course():
    form = CreateCourseForm()
    if form.validate_on_submit():
        course = Course(
            name=form.name.data,
            teacher_id=current_user.teacher.teacher_id,
            about_course=form.about_course.data,
            college=form.college.data,
            since=localtime()
        )
        db.session.add(course)
        db.session.commit()
        c = Course.query.offset(Course.query.count() - 1).first() #这里要从数据库中拿，因为course_id只有插入到数据库中才能确定
        create_message_table(c.course_id) #创建课程的时候要在mysql中建表
        create_resource_dir(c.course_id) #创建资源目录

        return redirect(url_for('course.index'))
    return render_template('course/create_course.html', form=form)



#TODO：课程资源,还没有实现分页功能
@course.route('/resources/<int:course_id>', methods=['GET'])
@login_required
def resources(course_id):
    dir = os.path.join(resources_base_dir, str(course_id))
    #文件列表，每一项是个元组，（文件名，文件绝对路径，文件后缀名（.jpg ...）,文件上传时间）
    file_list = zip(os.listdir(dir), [os.path.join(dir, filename) for filename in os.listdir(dir)],
                    [file_extension(filename) for filename in os.listdir(dir)],
                    [fileTime(os.path.join(dir, filename))[1] for filename in os.listdir(dir)])
    return render_template('course/resources.html', resources=file_list, course_id=course_id)


#下载资源
@course.route('/resources/<int:course_id>/download', methods=['GET'])
def download_resources(course_id):
    filename = request.args.get('filename') #拿到资源文件名
    dir = os.path.join(resources_base_dir, str(course_id)) #拿到对应课程的目录

    # 先判断要找的资源在不在服务器中，如果不在就404，这样也可以防止注入攻击
    if filename not in os.listdir(dir):
        return render_template('404.html', message='您要找的资源不存在')

    def send_file():
        store_path = os.path.join(dir, filename)
        with open(store_path, 'rb') as targetfile:
            while 1:
                data = targetfile.read(20 * 1024 * 1024)  # 每次读取20M
                if not data:
                    break
                yield data

    response = Response(send_file(), content_type='application/octet-stream')
    response.headers["Content-disposition"] = 'attachment; filename=%s' % filename  # 这行代码是为了下载时显示文件名
    return response


#TODO:显示出该课程所有考试信息
@course.route('/tests/<int:course_id>')
@login_required
def tests(course_id):
    all_tests = Test.query.filter_by(course_id=str(course_id)).all()
    allow = []
    if current_user.role.name == 'Student':
        for test in all_tests:
            record = CheckTest.query.filter_by(
                student_id=current_user.student.student_id,
                test_id=test.id
            ).first()
            if record is None:
                allow.append(True)
            else:
                if record.allow == True:
                    allow.append(True)
                else:
                    allow.append(False)
    else:
        allow = [True] * len(all_tests)
    return render_template('course/tests.html', all_tests=all_tests, course_id=course_id, allow=allow)


#TODO:发布考试
@course.route('/create-test/<int:course_id>', methods=['GET', 'POST'])
@permission_required(Permission.CREATETEST)
def create_test(course_id):
    return render_template('course/create_test.html', course_id=course_id)


#参加考试
@course.route('/join-test/<int:course_id>')
def join_test(course_id):
    test_name = request.values.get("test_name")
    test = Test.query.filter_by(course_id=course_id, name=test_name).first()
    content = json.loads(test.content)
    metadata = {
        "name": content['name'],
        "count": len(content['questions']),
        "course_id": course_id,
        "test_id": test.id,
    }
    question_count = len(content['questions'])
    questions = []
    for i in range(question_count):
        q = content['questions'][i]
        if q['type'] == 'simple':
            questions.append((q['id'], q['type'], q['content']['title']))
        else:
            questions.append((q['id'], q['type'], q['content']['title'], q['content']['A'], q['content']['B'], q['content']['C'], q['content']['D']))
    #open('test.txt', 'w').write(str(questions))
    return render_template('course/join_test.html', questions=questions, metadata=metadata)


#老师查看学生答题情况
@course.route('/show-all-answers/<int:course_id>')
@permission_required(Permission.CHECKANSWERS)
def show_all_answers(course_id):
    test_id = request.values.get("test_id")
    records = StudentCourse.query.filter_by(course_id=course_id).all()
    students = [i.student for i in records] #该门课的所有学生
    has_commit = []
    url = []
    for s in students:
        if Answer.query.filter_by(student_id=s.student_id, test_id=test_id).first(): #如果考过了
            url.append(url_for('course.show_answer', student_id=s.student_id, test_id=test_id))
        else:
            url.append('')
    return render_template('course/show_student_answers.html', students=students, test_id=test_id,
                           has_commit=has_commit, url=url)


#TODO:需要将学生的答案渲染出来
@course.route('/show-answer')
@permission_required(Permission.CHECKANSWERS)
def show_answer():
    student_id = request.values.get("student_id")
    test_id = request.values.get("test_id")
    answer = Answer.query.filter_by(
        student_id=student_id,
        test_id=test_id
    ).first().answer
    test = Test.query.filter_by(
        test_id=test_id
    ).first().content
    answer = json.loads(answer)
    test = json.loads(test)
    content = []
    for i in range(len(test['questions'])):
        content.append((i + 1, test['questions'][i]['content']['title'], answer['content'][i]['answer']))
    return render_template('course/answer.html', content=content)



#TODO:聊天室
#TODO：目前还不能防止用户进入自己课程之外的聊天室
@course.route('/chatroom/<int:course_id>')
@login_required
def chatroom(course_id):
    course = Course.query.filter_by(course_id=course_id).first()
    res = get_chat_history(course_id)
    chat_history = []
    for c in res:
        user = User.query.filter_by(id=c[0]).first()
        #昵称，头像，消息内容，时间戳
        chat_history.append((user.id, user.nickname, user.headicon_url, c[1], c[2]))
    if current_user.role.name == 'Student':
        courses = StudentCourse.query.filter_by(student_id=current_user.student.student_id).all()
        return render_template('course/chatroom.html', courses=[c.course for c in courses], course=course, chat_history=chat_history)
    elif current_user.role.name == 'Teacher':
        courses = current_user.teacher.courses

app/templates/course/announcement.html
{% extends "/base.html" %}
{% import "/_macros.html" as macros %}

{% block title %} 公告 {% endblock %}

{% block page_content %}
<div class="container navbar-default" style="height:100%;padding-top:30px;">
    <div class="container">
        {% for each in announcements %}
        <div style="padding-top:30px">
            <h4>{{ each.title }}</h4>
            <div style="width:100%;word-wrap:break-word">
                {{ each.body_html | safe }}
            </div>
            <p style="float:right">{{ each.timestamp }}</p>
        </div>
        {% endfor %}
    </div>
    <div class="pagination" style="margin-left:37%">
        {{ macros.pagination_widget(pagination, 'course.announcement', course_id=course_id) }}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>

</script>
{% endblock %} 

app/templates/course/answer.html
im answer

app/templates/course/chatroom.html
{% extends "/base.html" %}

{% block title %} Chat {% endblock %}

{% block page_content %}
    <div class="navbar-default" style="height:100%;padding-top:30px;">
        <div id="header"  style="padding-left:47%;padding-top:10px">
            <h1>{{ course.name }}</h1>
        </div>
        <div style="width: 100%; position: absolute; top:100px ; left: 0 ; bottom: 0; ">
            <div id="classes_menu" style="overflow-y:auto;background-color:#d1f1ef;height:100%;width:18%;float:left;">
                <!--classes list-->
                {% for course in courses %}
                <a href="{{ url_for('course.chatroom', course_id=course.course_id) }}">
                    <button type="button" class="btn btn-primary dropdown-toggle">
                        <div class="media-left">
                            <img src="{{ url_for('static', filename='img/suki.jpg') }}" class="media-object" style="width:80px">
                        </div>
                        <div class="media-body">
                            <p class="media-heading">{{ course.name }}</p>
                            <p>课程id: {{ course.course_id }}</p>
                            <p>授课老师: {{ course.teacher.user.name }}</p>
                        </div>
                    </button>
                </a>
                {% endfor %}
            </div>

            <div id="users_menu" style="overflow-y:auto;background-color:#a3fef8;height:100%;width:15%;float:left;">
                <!--users list-->
                {% for student in course.students %}
                <a href="{{ url_for('main.user', email=student.student.user.email) }}">
                    <button type="button" class="btn btn-default dropdown-toggle">
                        <div class="media-left">
                            <img src="{{ url_for('static', filename='img/suki.jpg') }}" class="media-object" style="width:50px">
                        </div>
                        <div class="media-body">
                            <p class="media-body" style="padding-top:17px">{{ student.student.user.nickname }}</p>
                        </div>
                    </button>
                </a>
                {% endfor %}
            </div>

            <!--chat list-->
            <div id="chat" style="overflow:auto;background-color:#EEEEEE;height:70%;width:67%;float:left;">
                <br />
                {% for each in chat_history %}
                {% if each[0] != current_user.id %}
                <!--other chat list-->
                <div>
                    <div style="width:7%;float:left">
                        <a href="#"><img src="{{ url_for('static', filename='headicon/'+each[2]) }}" style="width:100%"></a>
                    </div>
                    <div style="float:left;width:90%">
                        <div style="border-radius:15px;float:left;width:40%;background-color:#00dcf2">
                            <h4>{{ each[1] }} <span style="font-size: 12px">({{ each[4] }})</span></h4>
                            <p style="padding:0 5% 0 5%;word-wrap:break-word">{{ each[3] }}</p>
                        </div>
                    </div>
                    <div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                </div>

                {% else %}
                <!--self chat list-->
                <div>
                    <div style="width:7%;float:right">
                        <a href="#"><img src="{{ url_for('static', filename='headicon/'+each[2]) }}" style="width:100%"></a>
                    </div>
                    <div style="float:right;width:90%">
                        <div style="float:right;width:40%;border-radius:15px;background-color:#23ddaf">
                            <h4 style="padding-left:10%;">{{ each[1] }} <span style="font-size: 12px">({{ each[4] }})</span></h4>
                            <p style="padding:0 5% 0 5%; word-wrap:break-word;">{{ each[3] }}</p>
                        </div>
                    </div>
                    <div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                </div>
                {% endif %}

                {% endfor %}
            </div>


            <div id="footer" style="height:30%;width:67%;float:left;">
                <!-- button -->
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-default" onclick="javascrtpt:window.location.href='../announcement/{{ course.course_id }}'" style="height:50%;">公告</button>
                    <button type="button" class="btn btn-default" onclick="javascrtpt:window.location.href='../resources/{{ course.course_id }}'">课程资源</button>
                    <button type="button" class="btn btn-default" onclick="javascrtpt:window.location.href='../tests/{{ course.course_id }}'">在线考试</button>
                    {% if current_user.role.name == 'Teacher' %}
                    <button type="button" class="btn btn-default" onclick="javascrtpt:window.location.href='../publish-announcement/{{ course.course_id }}'">发布公告</button>
                    <button type="button" class="btn btn-default" onclick="javascrtpt:window.location.href='../publish-resource/{{ course.course_id }}'">上传资源</button>
                    <button type="button" class="btn btn-default" onclick="javascrtpt:window.location.href='../create-test/{{ course.course_id }}'">创建考试</button>
                    {% endif %}
                </div>
                <div class="btn-group btn-group-sm " style="float:right;">
                    <button type="button" class="btn btn-default" onclick="javascrtpt:window.location.href='../chat-history/{{ course.course_id }}'">历史记录</button>
                </div>
                <!-- input -->
                <textarea id="message" style="height:85%;width:100%;padding-top:20px"></textarea>
                <!-- send button -->
                <button id="send_message" type="button" class="btn btn-default" style="position: fixed;bottom: 10px;right:10px">发送</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"></script>
<script>
    $(document).ready(function() {
        //页面加载时滚动条自动下划到最新位置
        var chat = document.getElementById('chat');
        chat.scrollTop = chat.scrollHeight;

        socket = io.connect('http://' + document.domain + ':' + location.port);

        //接受广播
        socket.on('accept_connection', function (msg) {
            //alert(msg['user_id'] + '进入了聊天室');
            var div = `<div class="container col-xs-4 col-xs-offset-5" style="color:#a7a8a8">` + msg['nickname'] + `进入了聊天室</div><br/><br/>`;
            $('#chat').append(div);
            var chat = document.getElementById('chat');
            chat.scrollTop = chat.scrollHeight;
        });

        socket.on('accept_disconnection', function (msg) {
            //alert(msg['user_id'] + '离开了聊天室');
            var div = `<div class="container col-xs-4 col-xs-offset-5" style="color:#a7a8a8">` + msg['nickname'] + `离开了聊天室</div><br/><br/>`;
            $('#chat').append(div);
            var chat = document.getElementById('chat');
            chat.scrollTop = chat.scrollHeight;
        });

        socket.on('update_message', function (msg) {
            var div;
            if (msg['user_id'] == {{ current_user.id }}) {
                div = `<div>
                    <div style="width:7%;float:right">
                        <a href="#"><img src=../../static/headicon/` + msg['headicon_url'] +` style="width:100%"></a>
                    </div>
                    <div style="float:right;width:90%">
                        <div style="float:right;width:40%;border-radius:15px;background-color:#23ddaf">
                            <h4 style="padding-left:10%">` + msg['nickname'] + ` <span style="font-size: 12px">(` + msg['timestamp'] + `)</span></h4>
                            <p style="padding:0 5% 0 5%; word-wrap:break-word;">` + msg['content'] + `</p>
                        </div>
                    </div>
                    <div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                </div>`;
            } else {
                div = `<div>
                    <div style="width:7%;float:left">
                        <a href="#"><img src=../../static/headicon/` + msg['headicon_url'] +` style="width:100%"></a>
                    </div>
                    <div style="float:left;width:90%">
                        <div style="border-radius:15px;float:left;width:40%;background-color:#00dcf2">
                            <h4>` + msg['nickname'] + ` <span style="font-size: 12px">(` + msg['timestamp'] + `)</span></h4>
                            <p style="padding:0 5% 0 5%;word-wrap:break-word">` + msg['content'] + `</p>
                        </div>
                    </div>
                    <div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                </div>`;
            }

            $('#chat').append(div);
            //alert(div);

            //jquery不会操作，先用原生js替代
            var chat = document.getElementById('chat');
            chat.scrollTop = chat.scrollHeight;
        });

        //打开页面时发送连接请求
        socket.emit('connected', {
            'user_id': {{ current_user.id }},
            'room': '{{ course.course_id }}'
        });

        //点击发送按钮，发送消息
        $('button#send_message').click(function() {
            //消息内容不能为空
            if ($("#message").val() == '') {
                alert('内容不能为空');
                return;
            }
           socket.emit('send_message', {
               'content': $('textarea#message').val(),
               'user_id': '{{ current_user.id }}',
               'course_id': '{{ course.course_id }}',
           });
           $("#message").val("");
         });

    });


    window.onunload=function(e){
    　　socket.emit('disconnected', {
            'user_id': {{ current_user.id }},
            'room': '{{ course.course_id }}'
        });
    };




</script>
{% endblock %}

app/templates/course/courses.html
{% extends "/base.html" %}
{% import "/_macros.html" as macros %}
{% block title %}course_list{% endblock %}

{% block content %}
<div class="container navbar-default" style="height:100%;padding-top:30px;">
    <div class="container">
        {% for each in courses %}
        <div style="padding-top:60px;padding-bottom:30px">
            <div class="media-left">
                <a href="#"><img src="{{ url_for('static', filename='img/suki.jpg') }}" class="media-object" style="width:150px"></a>
            </div>
            <div class="media-body">
                <a href="{{ url_for('course.chatroom', course_id=each.course_id) }}"><h4 class="media-heading">{{ loop.index }}:{{ each.name }}(课程id: {{ each.course_id }})</h4></a>
                <a href="{{ url_for('main.user', email=each.teacher.user.email) }}"><p>授课老师:{{ each.teacher.user.name }}</p></a>
                <p>人数:{{ each.students.count() }}</p>
                <p>课程介绍:{{ each.about_course }}</p>
                <a id="{{ each.course_id }}" type="button" class="btn btn-default btn-lg" href="{{ url_for('course.join_course', course_id=each.course_id) }}">加入</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/course/create_course.html
{% extends "/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}创建课程{% endblock %}

{% block content %}
<div class="col-md-4 col-md-offset-4" style="padding-top:20%">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/course/join_course.html
{% extends "/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Join Course{% endblock %}

{% block content %}
<div class="col-md-4 col-md-offset-4" style="padding-top:20%">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/course/publish_announcement.html
{% extends "/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}发布公告{% endblock %}

{% block content %}
<div class="col-md-4 col-md-offset-4" style="padding-top:20%">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/course/publish_resource.html
{% extends "/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}发布资源{% endblock %}

{% block content %}
<div class="col-md-4 col-md-offset-4" style="padding-top:20%">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/course/query_course.html
{% extends "/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Join Course{% endblock %}

{% block content %}
<div class="col-md-4 col-md-offset-4" style="padding-top:20%">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/course/show_student_answers.html
{% for student in students %}
<a href="{{ url_for('course.show_answer', student_id=student.student_id, test_id=test_id) }}"></a>
<br>
{% endfor %}
qqqqq